<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">readFileWithFilter</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4KCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0
Q3Vyc29yKCk7ClN0cmluZyBmbmFtZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcocGlwZWxpbmVDdXJz
b3IsICJmbmFtZSIpOwpTdHJpbmdbXSBmaWx0ZXJzID0gSURhdGFVdGlsLmdldFN0cmluZ0FycmF5
KHBpcGVsaW5lQ3Vyc29yLCAiZmlsdGVycyIpOwpTdHJpbmcgbWF4TGluZXMgPSBJRGF0YVV0aWwu
Z2V0U3RyaW5nKHBpcGVsaW5lQ3Vyc29yLCAibWF4TGluZXMiKTsKCi8vIHByb2Nlc3MKCmludCBt
YXggPSAtMTsKCnRyeSB7bWF4ID0gSW50ZWdlci5wYXJzZUludChtYXhMaW5lcyk7fSBjYXRjaCAo
RXhjZXB0aW9uIGUpIHt9CgppZiAoZm5hbWUuY29udGFpbnMoIioiKSkgewoJLy8gbmVlZCB0byBm
aW5kIGZpbGUgZmlyc3QKCUZpbGUgZmlsZU5hbWVXaXRoV2l0aENhcmQgPSBuZXcgRmlsZShmbmFt
ZSk7CglGaWxlW10gZmlsZXMgPSBudWxsOwoJCglmaW5hbCBTdHJpbmcgbWF0Y2ggPSBuZXcgRmls
ZShmbmFtZSkuZ2V0TmFtZSgpOwoJCglpZiAoZmlsZU5hbWVXaXRoV2l0aENhcmQuaXNEaXJlY3Rv
cnkoKSkgewoJCWZpbGVzID0gZmlsZU5hbWVXaXRoV2l0aENhcmQubGlzdEZpbGVzKCk7Cgl9IGVs
c2UgewoJCWZpbGVzID0gZmlsZU5hbWVXaXRoV2l0aENhcmQuZ2V0UGFyZW50RmlsZSgpLmxpc3RG
aWxlcyhuZXcgRmlsZUZpbHRlcigpIHsKCQkJCgkJCUBPdmVycmlkZQoJCQlwdWJsaWMgYm9vbGVh
biBhY2NlcHQoRmlsZSBwYXRobmFtZSkgewoJCQkJU3lzdGVtLm91dC5wcmludGxuKHBhdGhuYW1l
LmdldE5hbWUoKSArICIgPT09ICIgKyBtYXRjaCk7CgkJCQkKCQkJCXJldHVybiAocGF0aG5hbWUu
Z2V0TmFtZSgpLm1hdGNoZXMobWF0Y2gpKTsKCQkJfQoJCX0pOwoJfQoJCglpZiAoZmlsZXMubGVu
Z3RoID4gMCkKCQlmbmFtZSA9IGZpbGVzW2ZpbGVzLmxlbmd0aC0xXS5nZXRBYnNvbHV0ZVBhdGgo
KTsKCQp9CgpTdHJpbmdbXSBtYXRjaGVkTGluZXMgPSByZWFkRmlsZUFzU3RyaW5nTGlzdChmbmFt
ZSwgZmlsdGVycywgbWF4KTsKCi8vIHBpcGVsaW5lIG91dAoKSURhdGFVdGlsLnB1dChwaXBlbGlu
ZUN1cnNvciwgIm1hdGNoZWRGaWxlIiwgZm5hbWUpOwpJRGF0YVV0aWwucHV0KHBpcGVsaW5lQ3Vy
c29yLCAibWF0Y2hlZEZpbGVOYW1lIiwgbmV3IEZpbGUoZm5hbWUpLmdldE5hbWUoKSk7CklEYXRh
VXRpbC5wdXQocGlwZWxpbmVDdXJzb3IsICJtYXRjaGVkTGluZXMiLCBtYXRjaGVkTGluZXMpOwpJ
RGF0YVV0aWwucHV0KHBpcGVsaW5lQ3Vyc29yLCAibWF0Y2hlZENvdW50IiwgIiIgKyBtYXRjaGVk
TGluZXMubGVuZ3RoKTsKcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOwoKCQ==</value>
</Values>
