<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">readFileWithFilter</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4KCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0
Q3Vyc29yKCk7ClN0cmluZyBmbmFtZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcocGlwZWxpbmVDdXJz
b3IsICJmbmFtZSIpOwpTdHJpbmdbXSBmaWx0ZXJzID0gSURhdGFVdGlsLmdldFN0cmluZ0FycmF5
KHBpcGVsaW5lQ3Vyc29yLCAiZmlsdGVycyIpOwpTdHJpbmcgbWF4TGluZXMgPSBJRGF0YVV0aWwu
Z2V0U3RyaW5nKHBpcGVsaW5lQ3Vyc29yLCAibWF4TGluZXMiKTsKCi8vIHByb2Nlc3MKCmludCBt
YXggPSAtMTsKClN5c3RlbS5vdXQucHJpbnRsbigiZm5hbWUgIiArIGZuYW1lKTsKCnRyeSB7bWF4
ID0gSW50ZWdlci5wYXJzZUludChtYXhMaW5lcyk7fSBjYXRjaCAoRXhjZXB0aW9uIGUpIHt9Cgpp
ZiAoZm5hbWUuY29udGFpbnMoIioiKSkgewoJLy8gbmVlZCB0byBmaW5kIGZpbGUgZmlyc3QKCUZp
bGUgZmlsZU5hbWVXaXRoV2l0aENhcmQgPSBuZXcgRmlsZShmbmFtZSk7CglGaWxlW10gZmlsZXMg
PSBudWxsOwoJCglmaW5hbCBTdHJpbmcgbWF0Y2ggPSBuZXcgRmlsZShmbmFtZSkuZ2V0TmFtZSgp
OwoJCglpZiAoZmlsZU5hbWVXaXRoV2l0aENhcmQuaXNEaXJlY3RvcnkoKSkgewoJCWZpbGVzID0g
ZmlsZU5hbWVXaXRoV2l0aENhcmQubGlzdEZpbGVzKCk7Cgl9IGVsc2UgewoJCWZpbGVzID0gZmls
ZU5hbWVXaXRoV2l0aENhcmQuZ2V0UGFyZW50RmlsZSgpLmxpc3RGaWxlcyhuZXcgRmlsZUZpbHRl
cigpIHsKCQkJCgkJCUBPdmVycmlkZQoJCQlwdWJsaWMgYm9vbGVhbiBhY2NlcHQoRmlsZSBwYXRo
bmFtZSkgewoJCQkJU3lzdGVtLm91dC5wcmludGxuKHBhdGhuYW1lLmdldE5hbWUoKSArICIgPT09
ICIgKyBtYXRjaCk7CgkJCQkKCQkJCXJldHVybiAocGF0aG5hbWUuZ2V0TmFtZSgpLm1hdGNoZXMo
bWF0Y2gpKTsKCQkJfQoJCX0pOwoJfQoJCglpZiAoZmlsZXMgIT0gbnVsbCAmJiBmaWxlcy5sZW5n
dGggPiAwKQoJCWZuYW1lID0gZmlsZXNbZmlsZXMubGVuZ3RoLTFdLmdldEFic29sdXRlUGF0aCgp
OwoJCn0KClN0cmluZ1tdIG1hdGNoZWRMaW5lcyA9IHJlYWRGaWxlQXNTdHJpbmdMaXN0KGZuYW1l
LCBmaWx0ZXJzLCBtYXgpOwoKLy8gcGlwZWxpbmUgb3V0CgpJRGF0YVV0aWwucHV0KHBpcGVsaW5l
Q3Vyc29yLCAibWF0Y2hlZEZpbGUiLCBmbmFtZSk7CklEYXRhVXRpbC5wdXQocGlwZWxpbmVDdXJz
b3IsICJtYXRjaGVkRmlsZU5hbWUiLCBuZXcgRmlsZShmbmFtZSkuZ2V0TmFtZSgpKTsKSURhdGFV
dGlsLnB1dChwaXBlbGluZUN1cnNvciwgIm1hdGNoZWRMaW5lcyIsIG1hdGNoZWRMaW5lcyk7CklE
YXRhVXRpbC5wdXQocGlwZWxpbmVDdXJzb3IsICJtYXRjaGVkQ291bnQiLCAiIiArIG1hdGNoZWRM
aW5lcy5sZW5ndGgpOwpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7CgoJ</value>
</Values>
