<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">fileExists</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly9maWxlUGF0aCBwaXBlbGluZSBpbgoKSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBl
bGluZS5nZXRDdXJzb3IoKTsKU3RyaW5nCWZuYW1lID0gSURhdGFVdGlsLmdldFN0cmluZyhwaXBl
bGluZUN1cnNvciwgImZuYW1lIik7CgovLyBwcm9jZXMKCmJvb2xlYW4gZXhpc3RzID0gbmV3IEZp
bGUoZm5hbWUpLmV4aXN0cygpOwpib29sZWFuIGlzRGlyID0gbmV3IEZpbGUoZm5hbWUpLmlzRGly
ZWN0b3J5KCk7CgpTdHJpbmcgY2hpbGROYW1lID0gbnVsbDsKCmlmIChpc0RpcikgewpTdHJpbmdb
XSBmaWxlcyA9IG5ldyBGaWxlKGZuYW1lKS5saXN0KCk7CgppZiAoZmlsZXMubGVuZ3RoID4gMCkg
ewpjaGlsZE5hbWUgPSBmaWxlc1tmaWxlcy5sZW5ndGgtMV07Cn0gZWxzZSB7CmV4aXN0cyA9IGZh
bHNlOwp9Cn0KCi8vIHBpcGVsaW5lIG91dAoKSURhdGFVdGlsLnB1dChwaXBlbGluZUN1cnNvciwg
ImV4aXN0cyIsICIiICsgZXhpc3RzKTsKCmlmIChleGlzdHMpIHsKSURhdGFVdGlsLnB1dChwaXBl
bGluZUN1cnNvciwgImlzRGlyIiwgIiIgKyBpc0Rpcik7CgppZiAoY2hpbGROYW1lICE9IG51bGwp
IHsKSURhdGFVdGlsLnB1dChwaXBlbGluZUN1cnNvciwgImZvdW5kIiwgbmV3IEZpbGUobmV3IEZp
bGUoZm5hbWUpLCBjaGlsZE5hbWUpLmdldFBhdGgoKSk7Cn0KfQoKcGlwZWxpbmVDdXJzb3IuZGVz
dHJveSgpOw==</value>
</Values>
