<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">fileExists</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly9maWxlUGF0aCBwaXBlbGluZSBpbgoKSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBl
bGluZS5nZXRDdXJzb3IoKTsKU3RyaW5nCWZuYW1lID0gSURhdGFVdGlsLmdldFN0cmluZyhwaXBl
bGluZUN1cnNvciwgImZuYW1lIik7CgovLyBwcm9jZXNzCgpib29sZWFuIGV4aXN0cyA9IG5ldyBG
aWxlKGZuYW1lKS5leGlzdHMoKTsKYm9vbGVhbiBpc0RpciA9IG5ldyBGaWxlKGZuYW1lKS5pc0Rp
cmVjdG9yeSgpOwoKU3RyaW5nIGNoaWxkTmFtZSA9IG51bGw7CgppZiAoaXNEaXIpIHsKU3RyaW5n
W10gZmlsZXMgPSBuZXcgRmlsZShmbmFtZSkubGlzdCgpOwoKaWYgKGZpbGVzLmxlbmd0aCA+IDAp
IHsKY2hpbGROYW1lID0gZmlsZXNbZmlsZXMubGVuZ3RoLTFdOwp9IGVsc2UgewpleGlzdHMgPSBm
YWxzZTsKfQp9CgovLyBwaXBlbGluZSBvdXQKCklEYXRhVXRpbC5wdXQocGlwZWxpbmVDdXJzb3Is
ICJleGlzdHMiLCAiIiArIGV4aXN0cyk7CgppZiAoZXhpc3RzKSB7CklEYXRhVXRpbC5wdXQocGlw
ZWxpbmVDdXJzb3IsICJpc0RpciIsICIiICsgaXNEaXIpOwoKaWYgKGNoaWxkTmFtZSAhPSBudWxs
KSB7CklEYXRhVXRpbC5wdXQocGlwZWxpbmVDdXJzb3IsICJmb3VuZCIsIG5ldyBGaWxlKG5ldyBG
aWxlKGZuYW1lKSwgY2hpbGROYW1lKS5nZXRQYXRoKCkpOwp9Cn0KCnBpcGVsaW5lQ3Vyc29yLmRl
c3Ryb3koKTs=</value>
</Values>
