<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">readFile</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgYyA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwpTdHJpbmcgZm5hbWUgPSBJRGF0
YVV0aWwuZ2V0U3RyaW5nKGMsICJmbmFtZSIpOwpTdHJpbmcgbG9hZEFzID0gSURhdGFVdGlsLmdl
dFN0cmluZyhjLCAibG9hZEFzIik7ClN0cmluZyBpZ25vcmVFcnJvciA9IElEYXRhVXRpbC5nZXRT
dHJpbmcoYywgImlnbm9yZUVycm9yIik7CgppZiAoZm5hbWUgPT0gbnVsbCkKdGhyb3cgbmV3IFNl
cnZpY2VFeGNlcHRpb24oInByb3ZpZGUgZmlsZSBuYW1lIHBsZWFzZSIpOwoKLy8gcHJvY2VzcwoK
Ynl0ZVtdIGRhdGEgPSBudWxsOwpJbnB1dFN0cmVhbSBpbiA9IG51bGw7Cgp0cnkgewppZiAobG9h
ZEFzICE9IG51bGwgJiYgbG9hZEFzLmVxdWFsc0lnbm9yZUNhc2UoInN0cmVhbSIpKSB7CmluID0g
bmV3IEZpbGVJbnB1dFN0cmVhbShuZXcgRmlsZShmbmFtZSkpOwp9IGVsc2UgewpkYXRhID0gRmls
ZXMucmVhZEFsbEJ5dGVzKFBhdGhzLmdldChmbmFtZSkpOwp9Cn0gY2F0Y2ggKE5vU3VjaEZpbGVF
eGNlcHRpb24gZSApIHsKaWYgKGlnbm9yZUVycm9yID09IG51bGwgfHwgIWlnbm9yZUVycm9yLmVx
dWFsc0lnbm9yZUNhc2UoInRydWUiKSkKdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oZSk7Cn0g
Y2F0Y2ggKElPRXhjZXB0aW9uIGUpIHsKCnRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKGUpOwp9
CgovLyBwaXBlbGluZSBvdXQKCklEYXRhVXRpbC5wdXQoYywgIm5hbWUiLCBuZXcgRmlsZShmbmFt
ZSkuZ2V0TmFtZSgpKTsKCmlmIChkYXRhICE9IG51bGwpIHsKCmlmIChsb2FkQXMgIT0gbnVsbCAm
JiBsb2FkQXMuZXF1YWxzSWdub3JlQ2FzZSgic3RyaW5nIikpCklEYXRhVXRpbC5wdXQoYywgInN0
cmluZyIsIG5ldyBTdHJpbmcoZGF0YSkpOwplbHNlCklEYXRhVXRpbC5wdXQoYywgImJ5dGVzIiwg
ZGF0YSk7CmMuZGVzdHJveSgpOwp9IGVsc2UgewpJRGF0YVV0aWwucHV0KGMsICJzdHJlYW0iLCBp
bik7Cn0=</value>
</Values>
