#
# Argento Controller or Management Server host (if empty string will use the APM Controller as it's host)
#
# registration-url - for registration and heartbeats
# reporting-url - where to send recurring reports
# eventing-url - where to send events
#
# R&D Test Agent - non customer env
#
management_server_test:
  host: "https://localhost:8090/"
  registration-url: argentoMgmtService/api/management
  reporting-url: argentoMgmtService/api/report
  eventing-url: argentoMgmtService/api/event
#
# R&D Test Backend - non customer env
#
management_server_vimal:
  host: "https://abs:8123"
  registration-url: /argento-agent/v1/management
  reporting-url: /argento-agent/v1/report
  eventing-url: /argento-agent/v1/event
#
# Application Server Info
#
application_server_profiles:
  - name: jboss
    property-id: jboss.home.dir
    set-headers-on-request: false
  - name: weblogic
    property-id: WL_HOME
    set-headers-on-request: false
  - name: liberty
    property-id: wlp.install.dir
    set-headers-on-request: true
  - name: glassfish
    property-id: com.sun.aas.installRoot
    set-headers-on-request: false
  - name: jetty
    property-id: jetty.home
    set-headers-on-request: false
  - name: tomcat
    property-id: catalina.base
    set-headers-on-request: false
  - name: websphere
    property-id: was.install.root
    set-headers-on-request: true




